const data = {
  products: [
    {
      _id: "1",
      name: "Men's Cotton Hooded Sweatshirt",
      slug: "men-cotton-hooded-sweatshirt",
      category: "men_clothes_shirt",
      image: "/image/boyShirt1.png",
      price: 120,
      countInStock: 10,
      brand: "Scott International",
      rating: "5",
      numReviews: 10,
      description: "Men's Regular Fit T-Shirt",
    },
    {
      _id: "2",
      name: "Men's Cotton Hooded Sweatshirt",
      slug: "men-cotton-hooded-sweatshirt",
      category: "men_clothes_hoddy",
      image: "/image/boyShirt2.png",
      price: 140,
      countInStock: 10,
      brand: "Alan Jones Clothing",
      rating: "4.5",
      numReviews: 14,
      description: "Men's Cotton Hooded Sweatshirt",
    },
    {
      _id: "3",
      name: "EYEBOGLER",
      slug: "eyebogler",
      category: "men_clothes_shirt",
      image: "/image/boyShirt3.png",
      price: 100,
      countInStock: 10,
      brand: "EYEBOGLER",
      rating: "3.5",
      numReviews: 69,
      description: "Band Collar Men's T-Shirt(EBT325 & EBT325HS)",
    },
    {
      _id: "4",
      name: "AWG ALL WEATHER GEAR",
      slug: "awg-all-weather-gear",
      category: "men_clothes_shirt",
      image: "/image/boyShirt4.png",
      price: 145,
      countInStock: 10,
      numReviews: 22,
      brand: "AWG ALL WEATHER GEAR",
      rating: "3",
      description: "AWG Men's Stylish Polyester Sports Round Neck T-Shirt",
    },
    {
      _id: "5",
      name: "Dennis Lingo",
      slug: "dennis-lingo",
      category: "clothes_shirt",
      image: "/image/boyShirt5.png",
      price: 160,
      countInStock: 10,
      brand: "Dennis Lingo",
      rating: "4",
      numReviews: 36,
      description: "Men's Dennis Shirt (EBT325 & EBT325HS) (EBT325 & EBT325HS)",
    },

    {
      _id: "6",
      name: "AMERICAN CREW",
      slug: "american-crew",
      category: "clothes_shirt",
      image: "/image/boyShirt6.png",
      price: 220,
      countInStock: 10,
      brand: "AMERICAN CREW",
      rating: "5",
      numReviews: 49,
      description: "Men's Polo Collar Half Sleeve Striped Cotton Melange",
    },
    {
      _id: "7",
      name: "THE ARCHER",
      slug: "the-archer",
      category: "men_clothes_shirt",
      image: "/image/boyShirt7.png",
      price: 220,
      countInStock: 10,
      brand: "THE ARCHER",
      rating: "4",
      numReviews: 26,
      description: "Solid Men Hooded Neck with Mask T-Shirt",
    },
    {
      _id: "8",
      name: "Peter England",
      slug: "peter-england",
      category: "men_clothes_shirt",
      image: "/image/boyShirt8.png",
      price: 220,
      countInStock: 10,
      brand: "Peter England",
      rating: "3",
      numReviews: 10,
      description: "Men's Regular Cotton Stufed Shirt",
    },
  ],
};
export default data;
